import { ArrowRight, Plus, Users } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { Skeleton } from "../../components/ui/skeleton";
import { useStudents } from "../../hooks/use-students";
import { formatDate } from "../../lib/utils";

export function DashboardPage() {
  const students = useStudents();
  const recentStudents = students.data?.slice(0, 5) || [];
  return <div className="space-y-8"><section className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div className="max-w-xl space-y-2"><p className="text-sm font-semibold text-primary">Visão geral</p><h1 className="text-3xl font-bold tracking-[-0.025em] text-balance">Seu espaço começa pelos seus alunos.</h1><p className="text-base leading-7 text-muted-foreground">Tenha sua base organizada para encontrar rapidamente quem precisa da sua atenção.</p></div><Button asChild><Link to="/students/new"><Plus className="size-4" />Cadastrar aluno</Link></Button></section><Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Base de alunos</CardTitle><CardDescription>Cadastros que você pode consultar e atualizar.</CardDescription></div><div className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><Users className="size-5" /></div></CardHeader><CardContent>{students.isPending ? <div className="space-y-3"><Skeleton className="h-12 w-full" /><Skeleton className="h-12 w-full" /></div> : students.isError ? <p className="rounded-lg bg-destructive/10 p-3 text-sm leading-5 text-destructive">Não foi possível carregar seus alunos agora.</p> : recentStudents.length === 0 ? <div className="rounded-lg bg-muted/50 px-4 py-8 text-center"><p className="font-semibold">Sua base ainda está vazia.</p><p className="mt-1 text-sm text-muted-foreground">Cadastre seu primeiro aluno para começar.</p><Button asChild variant="secondary" className="mt-4"><Link to="/students/new">Cadastrar primeiro aluno</Link></Button></div> : <div className="space-y-1"><div className="mb-4 flex items-baseline gap-2"><span className="text-3xl font-bold tracking-tight">{students.data.length}</span><span className="text-sm text-muted-foreground">{students.data.length === 1 ? "aluno cadastrado" : "alunos cadastrados"}</span></div>{recentStudents.map((student) => <Link key={student.id} to={`/students/${student.id}`} className="flex items-center justify-between gap-4 rounded-lg px-3 py-3 transition-colors hover:bg-accent"><div className="min-w-0"><p className="truncate font-semibold">{student.name}</p><p className="text-xs text-muted-foreground">Atualizado em {formatDate(student.updatedAt)}</p></div><ArrowRight className="size-4 shrink-0 text-muted-foreground" /></Link>)}{students.data.length > recentStudents.length && <Button asChild variant="link" className="mt-3 px-3"><Link to="/students">Ver todos os alunos <ArrowRight className="size-4" /></Link></Button>}</div>}</CardContent></Card></div>;
}
